name: '🪲 Report a bug'
description: 'Report a bug that you have encountered'
title: 'bug: '
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please fill in each section completely, and [search in GitHub](https://github.com/drodil/backstage-plugin-toolbox/search?type=Issues)
        before reporting a new bug to avoid duplicates. Thank you!
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: '📝 Description & Context'
      placeholder: |
        Describe the observed behavior that you believe to be incorrect, as well as any additional context that might be useful in understanding the bug.

        e.g. "When I post a new question, it doesn't show up. This might be related to https://xkcd.com/1172"
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: '👍 Expected Behavior'
      placeholder: |
        Describe the behavior or result that you expected instead of the observed one.

        e.g. "I expect the post to be visible"
  - type: markdown
    attributes:
      value: '<br/>' # empty space
  - type: markdown
    attributes:
      value: |
        ## Reproducing the bug

        Explain the reproduction steps in as much detail as possible including backstage version and plugin version numbers.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: '🥾 Reproduction steps'
      description: 'How do you trigger this bug? Please walk us through it step by step.'
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'"
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Are you willing to submit PR?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - Undecided
        - Yes, and I have enough information to get started
        - Yes, but I would like some more guidance
        - No, but I'm happy to collaborate on a PR with someone else
        - No, I don't have time to work on this right now
    validations:
      required: true
